server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:
    datasource:
        name: driving
        url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        #最大
        maxActive: 20
        #初始化
        initialSize: 1
        # 配置获取连接等待超时的时间
        maxWait: 60000
        #最小
        minIdle: 1
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        connectionProperties:


    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    jmx:
      enabled: false
    output:
      ansi:
        enabled: always
    jackson:
      time-zone: GMT+8

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.school.driving.model

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

password:
  algorithmName: md5 #加密方式
  hashIterations : 1 #加密次数
  initialPassword: 123456 #初始密码